auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /var/loki  # Укажите подходящий путь
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: "2024-12-25"
      store: "tsdb"
      object_store: "filesystem"
      schema: "v13"
      index:
        prefix: "index_"
        period: 24h

limits_config:
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024
